// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmUWkFYQaAwbuybRKOBaYw7cA4hSCnI3w',
    appId: '1:704819857956:web:41944f335844e1feb266b1',
    messagingSenderId: '704819857956',
    projectId: 'finance-tracker-app-ea33b',
    authDomain: 'finance-tracker-app-ea33b.firebaseapp.com',
    storageBucket: 'finance-tracker-app-ea33b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0VOb0lyZdIDbB1WvN2i-p7pH0O-ohVpc',
    appId: '1:704819857956:android:95d68445452c9485b266b1',
    messagingSenderId: '704819857956',
    projectId: 'finance-tracker-app-ea33b',
    storageBucket: 'finance-tracker-app-ea33b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlKDFtvwNc_fXzce2T-vpyfA5N_eY02So',
    appId: '1:704819857956:ios:32e9c2e7a1f98987b266b1',
    messagingSenderId: '704819857956',
    projectId: 'finance-tracker-app-ea33b',
    storageBucket: 'finance-tracker-app-ea33b.firebasestorage.app',
    iosBundleId: 'com.example.financeTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlKDFtvwNc_fXzce2T-vpyfA5N_eY02So',
    appId: '1:704819857956:ios:32e9c2e7a1f98987b266b1',
    messagingSenderId: '704819857956',
    projectId: 'finance-tracker-app-ea33b',
    storageBucket: 'finance-tracker-app-ea33b.firebasestorage.app',
    iosBundleId: 'com.example.financeTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmUWkFYQaAwbuybRKOBaYw7cA4hSCnI3w',
    appId: '1:704819857956:web:6b68d9d3a61cd24eb266b1',
    messagingSenderId: '704819857956',
    projectId: 'finance-tracker-app-ea33b',
    authDomain: 'finance-tracker-app-ea33b.firebaseapp.com',
    storageBucket: 'finance-tracker-app-ea33b.firebasestorage.app',
  );
}
